# Generated by Django 4.0.4 on 2022-05-07 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritions',
            name='caffeine_mg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='drink_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritions', to='products.drinks'),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='one_serving_kca',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='protein_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='saturated_fat_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='size_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritions', to='products.sizes'),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='sodium_mg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='nutritions',
            name='sugars_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='size_fluid_ounce',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='size_ml',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
