# Generated by Django 4.0.4 on 2022-05-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_nutritions_caffeine_mg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy_drink',
            old_name='allergy_id',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='allergy_drink',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='nutritions',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='nutritions',
            old_name='size_id',
            new_name='size',
        ),
    ]
