# Generated by Django 4.0.4 on 2022-05-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_drinks_allergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='allergy',
            field=models.ManyToManyField(related_name='drinks', through='products.Allergy_drink', to='products.allergy'),
        ),
    ]
