# Generated by Django 4.0.4 on 2022-05-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_drinks_allergy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='allergy',
            new_name='allergyed',
        ),
    ]
