# Generated by Django 4.0.4 on 2022-05-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_allergy_drinks_allergyed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='allergyed',
            field=models.ManyToManyField(through='products.Allergy_drink', to='products.allergy'),
        ),
    ]
