# Generated by Django 4.0.4 on 2022-05-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_drinks_allergyed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='allergyed',
            field=models.ManyToManyField(related_name='drinks', through='products.Allergy_drink', to='products.allergy'),
        ),
    ]
