# Generated by Django 4.0.4 on 2022-05-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_drinks_allergyed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy_drink',
            old_name='drink',
            new_name='drinks',
        ),
    ]
