# Generated by Django 4.0.4 on 2022-05-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_drink_allergy_drink_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinkss', to='products.categories'),
        ),
    ]
