# Generated by Django 4.0.2 on 2022-05-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_allergy_drink_allergy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='allergyed',
        ),
        migrations.AddField(
            model_name='allergy',
            name='allergyed',
            field=models.ManyToManyField(through='products.Allergy_drink', to='products.Drinks'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.TextField(max_length=45),
        ),
    ]
